### ISSUE TITLE
ilen returns zero inside lambda

### ISSUE THREAD

**Issue by pmatos** [erikrose/more-itertools#155]
I am slightly confused but it seems there might be either a bug of some kind (possibly related to `more-itertools`) or a misunderstanding on my part.

Under python `3.6` shell:
```
>>> from itertools import islice
>>> from more_itertools import ilen
>>> iterable = [0, 40, 20, 30]
>>> ilen(iterable)
4
>>> i = 0
>>> slicesz=2
>>> slc = islice(iterable, i, slicesz)
>>> slc
<itertools.islice object at 0x7fce0964c728>
>>> ilen(slc)
2
>>> avg = lambda l: sum(l)/ilen(l)
>>> avg(slc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
ZeroDivisionError: division by zero
```

How can `ilen` return zero inside the `lambda`?

**Comment by pmatos** [comment]
ok, my bad. `ilen` consumes the iterable.
