### ISSUE TITLE
SyntaxError: invalid syntax - "yield from iterable"

### ISSUE THREAD

**Issue by AndrewPaglusch** [erikrose/more-itertools#354]
Hopefully this is enough information. Please let me know if any more can be provided that would make troubleshooting this easier. My guess is that this has something to do with commit 5be161892cf05ea210d927bd585409014169740d.

Up-to-date CentOS 7
```
[root@awxtest awxcompose]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
```

```
[root@awxtest awxcompose]# uname -a
Linux awxtest 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Up-to-date more-itertools
```
[root@awxtest awxcompose]# pip list 2>&1 | grep more-itertools
more-itertools                     8.0.2
```

```
[root@awxtest awxcompose]# pip install more-itertools -U 2>/dev/null
Requirement already up-to-date: more-itertools in /usr/lib/python2.7/site-packages (8.0.2)
```

Up-to-date Python 2
```
[root@awxtest awxcompose]# python -V
Python 2.7.5
```

```
[root@awxtest awxcompose]# python -c "import more_itertools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File "/usr/lib/python2.7/site-packages/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
```

**Comment by AndrewPaglusch** [comment]
Closing. I now see that `more-itertools` no longer supports Python 2.

**Comment by cholpona** [comment]
@AndrewPaglusch how did you resolve that  more-itertools is no longer supports Python 2? Did you switch to Python 3 or found another way ?

**Comment by bbayles** [comment]
Install version 5.0.0.
