### ISSUE TITLE
SyntaxError: invalid syntax - yield from iterable

### ISSUE THREAD

**Issue by claudiamaximus** [erikrose/more-itertools#355]
more-itertools version - 8.0.2
python version - 3.6.8

**Requirements.txt:**
```
alembic==1.3.1
amqp==2.5.2
billiard==3.6.1.0
blinker==1.4
celery==4.3.0
certifi==2019.6.16
chardet==3.0.4
Click==7.0
colorama==0.4.1
Flask==1.1.1
Flask-Mail==0.9.1
Flask-Migrate==2.5.2
Flask-SQLAlchemy==2.4.1
idna==2.8
importlib-metadata==1.3.0
itsdangerous==1.1.0
Jinja2==2.10.1
kombu==4.6.7
Mako==1.1.0
MarkupSafe==1.1.1
more-itertools==8.0.2
pymaging==0.1
pymaging-png==0.1
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
qrcode==6.1
razorpay==1.2.0
requests==2.22.0
six==1.12.0
SQLAlchemy==1.3.11
urllib3==1.25.3
vine==1.3.0
Werkzeug==0.15.5
zipp==0.6.0
```

**__init__.py**
```python
...
celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)
...
```

**views/home.py**
```python
...
r = send_mail(email).delay(10, 20)
...
@celery.task
def send_mail(email):
    # email stuff
```

When I run the app, I get the following traceback!

```
[838493]  mod_wsgi (pid=12557): Exception occurred processing WSGI script '/var/www/myapp.com/public_html/myapp.wsgi'.
[838556]  Traceback (most recent call last):
[838580]    File "/var/www/myapp.com/public_html/myapp.wsgi", line 4, in <module>
[838617]      from myapp import app as application
[838626]    File "/var/www/myapp.com/public_html/myapp/__init__.py", line 13, in <module>
[838642]      from celery import Celery
[838650]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/celery/local.py", line 509, in __getattr__
[838665]      module = __import__(self._object_origins[name], None, None, [name])
[838672]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/celery/app/__init__.py", line 5, in <module>
[838686]      from celery import _state
[838693]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/celery/_state.py", line 17, in <module>
[838705]      from celery.utils.threads import LocalStack
[838712]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/celery/utils/__init__.py", line 8, in <module>
[838726]      from .functional import memoize  # noqa
[838745]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/celery/utils/functional.py", line 10, in <module>
[838759]      from kombu.utils.functional import (LRUCache, dictfilter, is_list, lazy,
[838766]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/kombu/utils/__init__.py", line 5, in <module>
[838779]      from .compat import fileno, maybe_fileno, nested, register_after_fork
[838786]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/kombu/utils/compat.py", line 14, in <module>
[838798]      import importlib_metadata
[838805]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 9, in <module>
[838818]      import zipp
[838825]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/zipp.py", line 12, in <module>
[838844]      import more_itertools
[838868]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/more_itertools/__init__.py", line 1, in <module>
[838893]      from .more import *  # noqa
[838939]    File "/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/more_itertools/more.py", line 460
[838946]      yield from iterable
[838950]               ^
[838955]  SyntaxError: invalid syntax
```

**WSGI configuration:**
```
WSGIDaemonProcess myapp user=myuser group=sudo threads=5 python-path=/var/www/myapp.com:/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/

WSGIScriptAlias / /var/www/myapp.com/public_html/myapp.wsgi
```

**sys.version**

`3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]`

**Comment by MSeifert04** [comment]
Is it possible that your mod_wsgi runs another Python (maybe Python 2.x)? See for example [this StackOverflow answer](https://stackoverflow.com/a/31195186/5393381):

> Is the mod_wsgi even compiled for the version of Python you want to use? It is a common mistake that people don't realise that mod_wsgi is actually for a different Python version and so not using the same Python installation as you expect and therefore using different versions of packages.

**Comment by claudiamaximus** [comment]
Recompiled mod_wsgi and confirmed that it runs Python v3.6 with `mod_wsgi-express module-config`.

The output is:

```
LoadModule wsgi_module "/home/myuser/.local/lib/python3.6/site-packages/mod_wsgi/server/mod_wsgi-py36.cpython-36m-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
```

My mod_wsgi conf:

```
<VirtualHost *:80>
    ServerAdmin admin@myapp.com
    ServerName myapp.com

    WSGIDaemonProcess myapp user=myuser group=sudo threads=5 python-path=/var/www/myapp.com:/var/www/myapp.com/public_html/venv/lib/python3.6/site-packages/
    WSGIScriptAlias / /var/www/myapp.com/public_html/myapp.wsgi

    DocumentRoot /var/www/myapp.com/public_html
    <Directory /var/www/myapp.com/public_html>
        WSGIProcessGroup myapp
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
        WSGIScriptReloading On
    </Directory>
</VirtualHost>
```

myapp.wsgi:
```
import sys
sys.path.insert(0, "/var/www/myapp.com/public_html/")

from myapp import app as application

from werkzeug.debug import DebuggedApplication
application = DebuggedApplication(application, True)
```

**Comment by gnuowned** [comment]
Python 2.7.17
more-itertools 8.02
I see the same issue trying to import acitoolkit (from cisco): 

`Python 2.7.17 (default, Oct 24 2019, 12:57:38)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from acitoolkit import acitoolkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/acitoolkit/__init__.py", line 30, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/acitoolkit/aciFaults.py", line 6, in <module>
  File "/Users/migbaraj/ansible/servers_casa/hello_network/py2-venv/lib/python2.7/site-packages/jsonschema-3.2.0-py2.7.egg/jsonschema/__init__.py", line 33, in <module>
    import importlib_metadata as metadata
  File "/Users/migbaraj/ansible/servers_casa/hello_network/py2-venv/lib/python2.7/site-packages/importlib_metadata-1.3.0-py2.7.egg/importlib_metadata/__init__.py", line 9, in <module>
    import zipp
  File "/Users/migbaraj/ansible/servers_casa/hello_network/py2-venv/lib/python2.7/site-packages/zipp-0.6.0-py2.7.egg/zipp.py", line 12, in <module>
    import more_itertools
  File "build/bdist.macosx-10.15-x86_64/egg/more_itertools/__init__.py", line 1, in <module>
  File "/Users/migbaraj/ansible/servers_casa/hello_network/py2-venv/lib/python2.7/site-packages/more_itertools-8.0.2-py2.7.egg/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax
>>>`

**Comment by gnuowned** [comment]
Happens the same by just importing more_intertools:

`import more_itertools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.15-x86_64/egg/more_itertools/__init__.py", line 1, in <module>
  File "/Users/migbaraj/ansible/servers_casa/hello_network/py2-venv/lib/python2.7/site-packages/more_itertools-8.0.2-py2.7.egg/more_itertools/more.py", line 460
    yield from iterable
             ^
SyntaxError: invalid syntax`

**Comment by bbayles** [comment]
@MSeifert04 is correct; this is because `more-itertools` no longer supports Python 2.7. You can pin the `5.0.0` version to keep using it.

**Comment by webknjaz** [comment]
Cross-posting a similar Python 3.5 bug: https://github.com/more-itertools/more-itertools/issues/578.
